#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqtoSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sample")]
	public partial class SampleDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdepartment(department instance);
    partial void Updatedepartment(department instance);
    partial void Deletedepartment(department instance);
    partial void Insertstaff_Master(staff_Master instance);
    partial void Updatestaff_Master(staff_Master instance);
    partial void Deletestaff_Master(staff_Master instance);
    partial void Insertemp(emp instance);
    partial void Updateemp(emp instance);
    partial void Deleteemp(emp instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    #endregion
		
		public SampleDBDataContext() : 
				base(global::LinqtoSql.Properties.Settings.Default.sampleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SampleDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SampleDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SampleDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SampleDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<department> departments
		{
			get
			{
				return this.GetTable<department>();
			}
		}
		
		public System.Data.Linq.Table<staff_Master> staff_Masters
		{
			get
			{
				return this.GetTable<staff_Master>();
			}
		}
		
		public System.Data.Linq.Table<emp> emps
		{
			get
			{
				return this.GetTable<emp>();
			}
		}
		
		public System.Data.Linq.Table<EmpLog> EmpLogs
		{
			get
			{
				return this.GetTable<EmpLog>();
			}
		}
		
		public System.Data.Linq.Table<saample> saamples
		{
			get
			{
				return this.GetTable<saample>();
			}
		}
		
		public System.Data.Linq.Table<saample2> saample2s
		{
			get
			{
				return this.GetTable<saample2>();
			}
		}
		
		public System.Data.Linq.Table<sample> samples
		{
			get
			{
				return this.GetTable<sample>();
			}
		}
		
		public System.Data.Linq.Table<stud> studs
		{
			get
			{
				return this.GetTable<stud>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.department")]
	public partial class department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _deptnos;
		
		private string _deparname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndeptnosChanging(long value);
    partial void OndeptnosChanged();
    partial void OndeparnameChanging(string value);
    partial void OndeparnameChanged();
    #endregion
		
		public department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptnos", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long deptnos
		{
			get
			{
				return this._deptnos;
			}
			set
			{
				if ((this._deptnos != value))
				{
					this.OndeptnosChanging(value);
					this.SendPropertyChanging();
					this._deptnos = value;
					this.SendPropertyChanged("deptnos");
					this.OndeptnosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deparname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string deparname
		{
			get
			{
				return this._deparname;
			}
			set
			{
				if ((this._deparname != value))
				{
					this.OndeparnameChanging(value);
					this.SendPropertyChanging();
					this._deparname = value;
					this.SendPropertyChanged("deparname");
					this.OndeparnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staff_Master")]
	public partial class staff_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Staff_Code;
		
		private string _Staff_Name;
		
		private System.Nullable<int> _Design_Code;
		
		private System.Nullable<int> _Dept_Code;
		
		private System.Nullable<System.DateTime> _Staff_dob;
		
		private System.Nullable<System.DateTime> _Hiredate;
		
		private System.Nullable<int> _Mgr_code;
		
		private System.Nullable<int> _Staff_sal;
		
		private string _Staff_address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaff_CodeChanging(int value);
    partial void OnStaff_CodeChanged();
    partial void OnStaff_NameChanging(string value);
    partial void OnStaff_NameChanged();
    partial void OnDesign_CodeChanging(System.Nullable<int> value);
    partial void OnDesign_CodeChanged();
    partial void OnDept_CodeChanging(System.Nullable<int> value);
    partial void OnDept_CodeChanged();
    partial void OnStaff_dobChanging(System.Nullable<System.DateTime> value);
    partial void OnStaff_dobChanged();
    partial void OnHiredateChanging(System.Nullable<System.DateTime> value);
    partial void OnHiredateChanged();
    partial void OnMgr_codeChanging(System.Nullable<int> value);
    partial void OnMgr_codeChanged();
    partial void OnStaff_salChanging(System.Nullable<int> value);
    partial void OnStaff_salChanged();
    partial void OnStaff_addressChanging(string value);
    partial void OnStaff_addressChanged();
    #endregion
		
		public staff_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Staff_Code
		{
			get
			{
				return this._Staff_Code;
			}
			set
			{
				if ((this._Staff_Code != value))
				{
					this.OnStaff_CodeChanging(value);
					this.SendPropertyChanging();
					this._Staff_Code = value;
					this.SendPropertyChanged("Staff_Code");
					this.OnStaff_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Staff_Name
		{
			get
			{
				return this._Staff_Name;
			}
			set
			{
				if ((this._Staff_Name != value))
				{
					this.OnStaff_NameChanging(value);
					this.SendPropertyChanging();
					this._Staff_Name = value;
					this.SendPropertyChanged("Staff_Name");
					this.OnStaff_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Design_Code", DbType="Int")]
		public System.Nullable<int> Design_Code
		{
			get
			{
				return this._Design_Code;
			}
			set
			{
				if ((this._Design_Code != value))
				{
					this.OnDesign_CodeChanging(value);
					this.SendPropertyChanging();
					this._Design_Code = value;
					this.SendPropertyChanged("Design_Code");
					this.OnDesign_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_Code", DbType="Int")]
		public System.Nullable<int> Dept_Code
		{
			get
			{
				return this._Dept_Code;
			}
			set
			{
				if ((this._Dept_Code != value))
				{
					this.OnDept_CodeChanging(value);
					this.SendPropertyChanging();
					this._Dept_Code = value;
					this.SendPropertyChanged("Dept_Code");
					this.OnDept_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_dob", DbType="Date")]
		public System.Nullable<System.DateTime> Staff_dob
		{
			get
			{
				return this._Staff_dob;
			}
			set
			{
				if ((this._Staff_dob != value))
				{
					this.OnStaff_dobChanging(value);
					this.SendPropertyChanging();
					this._Staff_dob = value;
					this.SendPropertyChanged("Staff_dob");
					this.OnStaff_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hiredate", DbType="Date")]
		public System.Nullable<System.DateTime> Hiredate
		{
			get
			{
				return this._Hiredate;
			}
			set
			{
				if ((this._Hiredate != value))
				{
					this.OnHiredateChanging(value);
					this.SendPropertyChanging();
					this._Hiredate = value;
					this.SendPropertyChanged("Hiredate");
					this.OnHiredateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mgr_code", DbType="Int")]
		public System.Nullable<int> Mgr_code
		{
			get
			{
				return this._Mgr_code;
			}
			set
			{
				if ((this._Mgr_code != value))
				{
					this.OnMgr_codeChanging(value);
					this.SendPropertyChanging();
					this._Mgr_code = value;
					this.SendPropertyChanged("Mgr_code");
					this.OnMgr_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_sal", DbType="Int")]
		public System.Nullable<int> Staff_sal
		{
			get
			{
				return this._Staff_sal;
			}
			set
			{
				if ((this._Staff_sal != value))
				{
					this.OnStaff_salChanging(value);
					this.SendPropertyChanging();
					this._Staff_sal = value;
					this.SendPropertyChanged("Staff_sal");
					this.OnStaff_salChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_address", DbType="NVarChar(50)")]
		public string Staff_address
		{
			get
			{
				return this._Staff_address;
			}
			set
			{
				if ((this._Staff_address != value))
				{
					this.OnStaff_addressChanging(value);
					this.SendPropertyChanging();
					this._Staff_address = value;
					this.SendPropertyChanged("Staff_address");
					this.OnStaff_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.emp")]
	public partial class emp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _empno;
		
		private string _empname;
		
		private long _ph;
		
		private System.Nullable<long> _deptno;
		
		private string _design;
		
		private System.Nullable<int> _manager;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnempnoChanging(long value);
    partial void OnempnoChanged();
    partial void OnempnameChanging(string value);
    partial void OnempnameChanged();
    partial void OnphChanging(long value);
    partial void OnphChanged();
    partial void OndeptnoChanging(System.Nullable<long> value);
    partial void OndeptnoChanged();
    partial void OndesignChanging(string value);
    partial void OndesignChanged();
    partial void OnmanagerChanging(System.Nullable<int> value);
    partial void OnmanagerChanged();
    #endregion
		
		public emp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empno", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long empno
		{
			get
			{
				return this._empno;
			}
			set
			{
				if ((this._empno != value))
				{
					this.OnempnoChanging(value);
					this.SendPropertyChanging();
					this._empno = value;
					this.SendPropertyChanged("empno");
					this.OnempnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empname", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string empname
		{
			get
			{
				return this._empname;
			}
			set
			{
				if ((this._empname != value))
				{
					this.OnempnameChanging(value);
					this.SendPropertyChanging();
					this._empname = value;
					this.SendPropertyChanged("empname");
					this.OnempnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph", DbType="BigInt NOT NULL")]
		public long ph
		{
			get
			{
				return this._ph;
			}
			set
			{
				if ((this._ph != value))
				{
					this.OnphChanging(value);
					this.SendPropertyChanging();
					this._ph = value;
					this.SendPropertyChanged("ph");
					this.OnphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptno", DbType="BigInt")]
		public System.Nullable<long> deptno
		{
			get
			{
				return this._deptno;
			}
			set
			{
				if ((this._deptno != value))
				{
					this.OndeptnoChanging(value);
					this.SendPropertyChanging();
					this._deptno = value;
					this.SendPropertyChanged("deptno");
					this.OndeptnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_design", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string design
		{
			get
			{
				return this._design;
			}
			set
			{
				if ((this._design != value))
				{
					this.OndesignChanging(value);
					this.SendPropertyChanging();
					this._design = value;
					this.SendPropertyChanged("design");
					this.OndesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager", DbType="Int")]
		public System.Nullable<int> manager
		{
			get
			{
				return this._manager;
			}
			set
			{
				if ((this._manager != value))
				{
					this.OnmanagerChanging(value);
					this.SendPropertyChanging();
					this._manager = value;
					this.SendPropertyChanged("manager");
					this.OnmanagerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmpLog")]
	public partial class EmpLog
	{
		
		private int _LogID;
		
		private int _EmpID;
		
		private string _Operation;
		
		private System.DateTime _UpdatedDate;
		
		public EmpLog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this._LogID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int NOT NULL")]
		public int EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this._EmpID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this._UpdatedDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saample")]
	public partial class saample
	{
		
		private string _name;
		
		private System.Nullable<int> _number;
		
		public saample()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int")]
		public System.Nullable<int> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saample2")]
	public partial class saample2
	{
		
		private string _name;
		
		private System.Nullable<int> _number;
		
		public saample2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int")]
		public System.Nullable<int> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sample")]
	public partial class sample
	{
		
		private string _name;
		
		private string _number;
		
		public sample()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(10)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stud")]
	public partial class stud
	{
		
		private System.Nullable<int> _rnos;
		
		private System.Nullable<System.DateTime> _dob;
		
		public stud()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnos", DbType="Int")]
		public System.Nullable<int> rnos
		{
			get
			{
				return this._rnos;
			}
			set
			{
				if ((this._rnos != value))
				{
					this._rnos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date")]
		public System.Nullable<System.DateTime> dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this._dob = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rno;
		
		private string _sname;
		
		private System.Nullable<System.DateTime> _dob;
		
		private string _addr;
		
		private string _email;
		
		private string _phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrnoChanging(int value);
    partial void OnrnoChanged();
    partial void OnsnameChanging(string value);
    partial void OnsnameChanged();
    partial void OndobChanging(System.Nullable<System.DateTime> value);
    partial void OndobChanged();
    partial void OnaddrChanging(string value);
    partial void OnaddrChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int rno
		{
			get
			{
				return this._rno;
			}
			set
			{
				if ((this._rno != value))
				{
					this.OnrnoChanging(value);
					this.SendPropertyChanging();
					this._rno = value;
					this.SendPropertyChanged("rno");
					this.OnrnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sname", DbType="VarChar(25)")]
		public string sname
		{
			get
			{
				return this._sname;
			}
			set
			{
				if ((this._sname != value))
				{
					this.OnsnameChanging(value);
					this.SendPropertyChanging();
					this._sname = value;
					this.SendPropertyChanged("sname");
					this.OnsnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date")]
		public System.Nullable<System.DateTime> dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addr", DbType="VarChar(50)")]
		public string addr
		{
			get
			{
				return this._addr;
			}
			set
			{
				if ((this._addr != value))
				{
					this.OnaddrChanging(value);
					this.SendPropertyChanging();
					this._addr = value;
					this.SendPropertyChanged("addr");
					this.OnaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
